sync:
  - file-path: ../web/apps/expenses/dist
    directory-name: app/src/main/assets/portals/expenses
  - file-path: ../web/apps/tasks/dist
    directory-name: app/src/main/assets/portals/tasks
  - file-path: ../web/apps/time-tracking/dist
    directory-name: app/src/main/assets/portals/time_tracking
